import { Injectable } from '@angular/core';
import { Country } from '../Clases/country';
import { State } from '../Clases/state'

@Injectable({
  providedIn: 'root'
})
export class JudeteService {

  constructor() { }

  getCountries() {
    return [
      new Country('Alba', 'Alba'),
      new Country('Arad', 'Arad'),
      new Country('Arges', 'Arges'),
      new Country('Bacau', 'Bacau'),
      new Country('Bihor', 'Bihor'),
      new Country('Bistrita - Nasaud', 'Bistrita - Nasaud'),
      new Country('Botosani', 'Botosani'),
      new Country('Braila', 'Braila'),
      new Country('Brasov', 'Brasov'),
      new Country('Bucuresti', 'Bucuresti'),
      new Country('Buzau', 'Buzau'),
      new Country('Calarasi', 'Calarasi'),
      new Country('Caras - Severin', 'Caras - Severin'),
      new Country('Cluj', 'Cluj'),
      new Country('Constanta', 'Constanta'),
      new Country('Covasna', 'Covasna'),
      new Country('Dambovita', 'Dambovita'),
      new Country('Dolj', 'Dolj'),
      new Country('Galati', 'Galati'),
      new Country('Giurgiu', 'Giurgiu'),
      new Country('Gorj', 'Gorj'),
      new Country('Harghita', 'Harghita'),
      new Country('Hunedoara', 'Hunedoara'),
      new Country('Ialomita', 'Ialomita'),
      new Country('Iasi', 'Iasi'),
      new Country('Ilfov', 'Ilfov'),
      new Country('Maramures', 'Maramures'),
      new Country('Mehedinti', 'Mehedinti'),
      new Country('Mures', 'Mures'),
      new Country('Neamt', 'Neamt'),
      new Country('Olt', 'Olt'),
      new Country('Prahova', 'Prahova'),
      new Country('Salaj', 'Salaj'),
      new Country('Satu - Mare', 'Satu - Mare'),
      new Country('Sibiu', 'Sibiu'),
      new Country('Suceava', 'Suceava'),
      new Country('Teleorman', 'Teleorman'),
      new Country('Timis', 'Timis'),
      new Country('Tulcea', 'Tulcea'),
      new Country('Valcea', 'Valcea'),
      new Country('Vaslui', 'Vaslui'),
      new Country('Vrancea', 'Vrancea'),
    ];
  }

  getStates() {
    return [
      new State(1, 'Alba', 'Alba Iulia'),
      new State(2, 'Alba', 'Sebes'),
      new State(3, 'Alba', 'Aiud'),
      new State(4, 'Alba', 'Cugir'),
      new State(5, 'Alba', 'Blaj'),
      new State(6, 'Alba', 'Ocna Mures'),
      new State(7, 'Alba', 'Zlatna'),
      new State(8, 'Alba', 'Campeni'),
      new State(9, 'Alba', 'Teius'),
      new State(10, 'Alba', 'Abrud'),
      new State(11, 'Alba', 'Baia de Aries'),

      new State(12, 'Arad', 'Arad'),
      new State(13, 'Arad', 'Pecica'),
      new State(14, 'Arad', 'Santana'),
      new State(15, 'Arad', 'Lipova'),
      new State(16, 'Arad', 'Ineu'),
      new State(17, 'Arad', 'Chisineu Cris'),
      new State(18, 'Arad', 'Nadlac'),
      new State(19, 'Arad', 'Curtici'),
      new State(20, 'Arad', 'Pancota'),
      new State(21, 'Arad', 'Sebis'),

      new State(22, 'Arges', 'Pitesti'),
      new State(23, 'Arges', 'Mioveni'),
      new State(24, 'Arges', 'Campulung'),
      new State(25, 'Arges', 'Curtea de Arges'),
      new State(26, 'Arges', 'Stefanesti'),
      new State(27, 'Arges', 'Costesti'),
      new State(28, 'Arges', 'Topoloveni'),

      new State(29, 'Bacau', 'Bacau'),
      new State(30, 'Bacau', 'Onesti'),
      new State(31, 'Bacau', 'Moinesti'),
      new State(32, 'Bacau', 'Comanesti'),
      new State(33, 'Bacau', 'Buhusi'),
      new State(34, 'Bacau', 'Darmanesti'),
      new State(35, 'Bacau', 'Targu Ocna'),
      new State(36, 'Bacau', 'Slanic-Moldova'),

      new State(37, 'Bihor', 'Oradea'),
      new State(38, 'Bihor', 'Salonta'),
      new State(39, 'Bihor', 'Marghita'),
      new State(40, 'Bihor', 'Sacueni'),
      new State(41, 'Bihor', 'Beius'),
      new State(42, 'Bihor', 'Valea lui Mihai'),
      new State(43, 'Bihor', 'Alesd'),
      new State(44, 'Bihor', 'Stei'),
      new State(45, 'Bihor', 'Vascau'),
      new State(46, 'Bihor', 'Nucet'),

      new State(47, 'Bistrita - Nasaud', 'Bistrita'),
      new State(48, 'Bistrita - Nasaud', 'Beclean'),
      new State(49, 'Bistrita - Nasaud', 'Sangeorz-Bai'),
      new State(50, 'Bistrita - Nasaud', 'Nasaud'),

      new State(51, 'Botosani', 'Botosani'),
      new State(52, 'Botosani', 'Dorohoi'),
      new State(53, 'Botosani', 'Darabani'),
      new State(54, 'Botosani', 'Flamanzi'),
      new State(55, 'Botosani', 'Saveni'),
      new State(56, 'Botosani', 'Stefanesti'),
      new State(57, 'Botosani', 'Bucecea'),

      new State(58, 'Braila', 'Braila'),
      new State(59, 'Braila', 'Ianca'),
      new State(60, 'Braila', 'Iusuratei'),
      new State(71, 'Braila', 'Faurei'),

      new State(72, 'Brasov', 'Brasov'),
      new State(73, 'Brasov', 'Fagaras'),
      new State(74, 'Brasov', 'Sacele'),
      new State(75, 'Brasov', 'Zarnesti'),
      new State(76, 'Brasov', 'Codlea'),
      new State(77, 'Brasov', 'Rasnov'),
      new State(78, 'Brasov', 'Victoria'),
      new State(79, 'Brasov', 'Rupea'),
      new State(80, 'Brasov', 'Ghimbav'),
      new State(81, 'Brasov', 'Predeal'),

      new State(82, 'Bucuresti', 'Bucuresti'),

      new State(83, 'Buzau', 'Buzau'),
      new State(84, 'Buzau', 'Ramnicu Sarat'),
      new State(85, 'Buzau', 'Nehoiu'),
      new State(86, 'Buzau', 'Patarlagele'),
      new State(87, 'Buzau', 'Pogoanele'),

      new State(88, 'Calarasi', 'Calarasi'),
      new State(89, 'Calarasi', 'Oltenita'),
      new State(90, 'Calarasi', 'Budesti'),
      new State(91, 'Calarasi', 'Fundulea'),
      new State(92, 'Calarasi', 'Lehliu-Gara'),

      new State(93, 'Caras - Severin', 'Resita'),
      new State(94, 'Caras - Severin', 'Caransebes'),
      new State(95, 'Caras - Severin', 'Bocsa'),
      new State(96, 'Caras - Severin', 'Moldova Noua'),
      new State(97, 'Caras - Severin', 'Oravita'),
      new State(98, 'Caras - Severin', 'Otelu'),
      new State(99, 'Caras - Severin', 'Rosu'),
      new State(100, 'Caras - Severin', 'Anina'),
      new State(101, 'Caras - Severin', 'Baile Herculane'),

      new State(102, 'Cluj', 'Cluj-Napoca'),
      new State(103, 'Cluj', 'Turda'),
      new State(104, 'Cluj', 'Dej'),
      new State(105, 'Cluj', 'Campia Turzii'),
      new State(106, 'Cluj', 'Gerla'),
      new State(107, 'Cluj', 'Huedin'),

      new State(108, 'Constanta', 'Constanta'),
      new State(109, 'Constanta', 'Medgidia'),
      new State(110, 'Constanta', 'Mangalia'),
      new State(111, 'Constanta', 'Navodari'),
      new State(112, 'Constanta', 'Cernavoda'),
      new State(113, 'Constanta', 'Ovidiu'),
      new State(114, 'Constanta', 'Murfatlar'),
      new State(115, 'Constanta', 'Harsova'),
      new State(116, 'Constanta', 'Eforie'),
      new State(117, 'Constanta', 'Techirgiol'),
      new State(118, 'Constanta', 'Baneasa'),
      new State(119, 'Constanta', 'Negru Voda'),

      new State(120, 'Covasna', 'Sfantu Georghe'),
      new State(121, 'Covasna', 'Targu Secuiesc'),
      new State(122, 'Covasna', 'Covasna'),
      new State(123, 'Covasna', 'Baraolt'),
      new State(124, 'Covasna', 'Intorsura Buzaului'),

      new State(125, 'Dambovita', 'Targoviste'),
      new State(126, 'Dambovita', 'Moreni'),
      new State(127, 'Dambovita', 'Pucioasa'),
      new State(128, 'Dambovita', 'Gaesti'),
      new State(129, 'Dambovita', 'Titu'),
      new State(130, 'Dambovita', 'Fieni'),
      new State(131, 'Dambovita', 'Racari'),

      new State(132, 'Dolj', 'Craiova'),
      new State(133, 'Dolj', 'Bailesti'),
      new State(134, 'Dolj', 'Calafat'),
      new State(135, 'Dolj', 'Filiasi'),
      new State(136, 'Dolj', 'Dabuleni'),
      new State(137, 'Dolj', 'Segarcea'),
      new State(138, 'Dolj', 'Bechet'),

      new State(139, 'Galati', 'Galati'),
      new State(140, 'Galati', 'Tecuci'),
      new State(141, 'Galati', 'Targu Bujor'),
      new State(142, 'Galati', 'Beresti'),

      new State(143, 'Giurgiu', 'Giurgiu'),
      new State(144, 'Giurgiu', 'Bolintin-Vale'),
      new State(145, 'Giurgiu', 'Mihailest'),

      new State(146, 'Gorj', 'Targu Jiu'),
      new State(147, 'Gorj', 'Motru'),
      new State(148, 'Gorj', 'Rovinari'),
      new State(149, 'Gorj', 'Bumbesti-Jiu'),
      new State(150, 'Gorj', 'Targu Carbunesti'),
      new State(151, 'Gorj', 'Turceni'),
      new State(152, 'Gorj', 'Tismana'),
      new State(153, 'Gorj', 'Novaci'),
      new State(154, 'Gorj', 'Ticleni'),

      new State(155, 'Harghita', 'Miecurea-Ciuc'),
      new State(156, 'Harghita', 'Odorheiu Secuiesc'),
      new State(157, 'Harghita', 'Gheorgheni'),
      new State(158, 'Harghita', 'Toplita'),
      new State(159, 'Harghita', 'Cristuru Secuiesc'),
      new State(160, 'Harghita', 'Vlahita'),
      new State(161, 'Harghita', 'Balan'),
      new State(162, 'Harghita', 'Borsec'),
      new State(163, 'Harghita', 'Tusnad'),

      new State(164, 'Hunedoara', 'Deva'),
      new State(165, 'Hunedoara', 'Hunedoara'),
      new State(166, 'Hunedoara', 'Petrosani'),
      new State(167, 'Hunedoara', 'Vulcan'),
      new State(168, 'Hunedoara', 'Lupeni'),
      new State(169, 'Hunedoara', 'Petrila'),
      new State(170, 'Hunedoara', 'Orastie'),
      new State(171, 'Hunedoara', 'Brad'),
      new State(172, 'Hunedoara', 'Simeria'),
      new State(173, 'Hunedoara', 'Calan'),
      new State(174, 'Hunedoara', 'Hateg'),
      new State(175, 'Hunedoara', 'Uricani'),
      new State(176, 'Hunedoara', 'Geoagiu'),
      new State(177, 'Hunedoara', 'Animoasa'),

      new State(178, 'Ialomita', 'Slobozia'),
      new State(179, 'Ialomita', 'Fetesti'),
      new State(180, 'Ialomita', 'Urziceni'),
      new State(181, 'Ialomita', 'Tandarei'),
      new State(182, 'Ialomita', 'Amara'),
      new State(183, 'Ialomita', 'Fierbinti-Targ'),
      new State(184, 'Ialomita', 'Cazanesti'),

      new State(185, 'Iasi', 'Iasi'),
      new State(186, 'Iasi', 'Pascani'),
      new State(187, 'Iasi', 'Harlau'),
      new State(188, 'Iasi', 'Targu Frumos'),
      new State(189, 'Iasi', 'Podu Iloaiei'),

      new State(190, 'Ilfov', 'Voluntari'),
      new State(191, 'Ilfov', 'Pantelimon'),
      new State(192, 'Ilfov', 'Buftea'),
      new State(193, 'Ilfov', 'Popesti-Leordeni'),
      new State(194, 'Ilfov', 'Bragadiru'),
      new State(195, 'Ilfov', 'Chitila'),
      new State(196, 'Ilfov', 'Otopeni'),
      new State(197, 'Ilfov', 'Magurele'),

      new State(198, 'Maramures', 'Baia Mare'),
      new State(199, 'Maramures', 'Sighetu Marmatiei'),
      new State(200, 'Maramures', 'Borsa'),
      new State(201, 'Maramures', 'Baia-Sprie'),
      new State(202, 'Maramures', 'Viseu de Sus'),
      new State(203, 'Maramures', 'Targu-Lapus'),
      new State(204, 'Maramures', 'Seini'),
      new State(205, 'Maramures', 'Somcuta Mare'),
      new State(206, 'Maramures', 'Ulmeni'),
      new State(207, 'Maramures', 'Tautii Magheraus'),
      new State(208, 'Maramures', 'Cavnic'),
      new State(209, 'Maramures', 'Salistea de Sus'),
      new State(210, 'Maramures', 'Dragomiresti'),

      new State(211, 'Mehedinti', 'Drobeta-Turnu Severin'),
      new State(212, 'Mehedinti', 'Strehaia'),
      new State(213, 'Mehedinti', 'Orsoha'),
      new State(214, 'Mehedinti', 'Baia de Arama'),
      new State(215, 'Mehedinti', 'Vanju Mare'),

      new State(216, 'Mures', 'Targu-Mures'),
      new State(217, 'Mures', 'Reghin'),
      new State(218, 'Mures', 'Sighisoara'),
      new State(219, 'Mures', 'Tarnaveni'),
      new State(220, 'Mures', 'Ludus'),
      new State(221, 'Mures', 'Sovata'),
      new State(222, 'Mures', 'Iernut'),
      new State(223, 'Mures', 'Sarmasu'),
      new State(224, 'Mures', 'Ungheni'),
      new State(225, 'Mures', 'Miercurea Nirajului'),
      new State(226, 'Mures', 'Sangeorgiu-de-Padure'),

      new State(227, 'Neamt', 'Piatra Neamt'),
      new State(228, 'Neamt', 'Roman'),
      new State(229, 'Neamt', 'Targu-Neamt'),
      new State(230, 'Neamt', 'Roznov'),
      new State(231, 'Neamt', 'Bicaz'),

      new State(232, 'Olt', 'Slatina'),
      new State(233, 'Olt', 'Caracal'),
      new State(234, 'Olt', 'Bals'),
      new State(235, 'Olt', 'Corabia'),
      new State(236, 'Olt', 'Scornicesti'),
      new State(237, 'Olt', 'Draganesti-Olt'),
      new State(238, 'Olt', 'Piatra Olt'),
      new State(239, 'Olt', 'Potcoava'),

      new State(240, 'Prahova', 'Ploiesti'),
      new State(242, 'Prahova', 'Campina'),
      new State(243, 'Prahova', 'Baicoi'),
      new State(244, 'Prahova', 'Breaza'),
      new State(245, 'Prahova', 'Mizil'),
      new State(246, 'Prahova', 'Comarnic'),
      new State(247, 'Prahova', 'Valenii de Munte'),
      new State(248, 'Prahova', 'Boldesti-Scaeni'),
      new State(249, 'Prahova', 'Urlati'),
      new State(250, 'Prahova', 'Sinaia'),
      new State(251, 'Prahova', 'Busteni'),
      new State(252, 'Prahova', 'Plopeni'),
      new State(253, 'Prahova', 'Slanic'),
      new State(254, 'Prahova', 'Azuga'),

      new State(255, 'Salaj', 'Zalau'),
      new State(256, 'Salaj', 'Simleu Silvaniei'),
      new State(257, 'Salaj', 'Jibon'),
      new State(258, 'Salaj', 'Cehu Silvaniei'),

      new State(259, 'Satu - Mare', 'Satu - Mare'),
      new State(260, 'Satu - Mare', 'Carei'),
      new State(261, 'Satu - Mare', 'Negresti-Oas'),
      new State(262, 'Satu - Mare', 'Tasnad'),
      new State(263, 'Satu - Mare', 'Livada'),
      new State(264, 'Satu - Mare', 'Ardud'),

      new State(265, 'Sibiu', 'Sibiu'),
      new State(266, 'Sibiu', 'Medias'),
      new State(267, 'Sibiu', 'Cisnadie'),
      new State(268, 'Sibiu', 'Avrig'),
      new State(269, 'Sibiu', 'Agnita'),
      new State(270, 'Sibiu', 'Dumbraveni'),
      new State(271, 'Sibiu', 'Talmaciu'),
      new State(272, 'Sibiu', 'Copsa Mica'),
      new State(273, 'Sibiu', 'Saliste'),
      new State(274, 'Sibiu', 'Miercurea Sibiului'),
      new State(275, 'Sibiu', 'Ocna Sibiului'),

      new State(276, 'Suceava', 'Suceava'),
      new State(278, 'Suceava', 'Falticeni'),
      new State(279, 'Suceava', 'Radauti'),
      new State(280, 'Suceava', 'Campulung Moldovenesc'),
      new State(281, 'Suceava', 'Vatra Dornei'),
      new State(282, 'Suceava', 'Vicovu de Sus'),
      new State(283, 'Suceava', 'Gura Humorului'),
      new State(284, 'Suceava', 'Dolhasca'),
      new State(285, 'Suceava', 'Liteni'),
      new State(286, 'Suceava', 'Salcea'),
      new State(287, 'Suceava', 'Siret'),
      new State(288, 'Suceava', 'Cajvana'),
      new State(289, 'Suceava', 'Frasin'),
      new State(290, 'Suceava', 'Brosteni'),
      new State(291, 'Suceava', 'Milisauti'),
      new State(292, 'Suceava', 'Solca'),


      new State(293, 'Teleorman', 'Alexandria'),
      new State(294, 'Teleorman', 'Rosiorii de Vede'),
      new State(295, 'Teleorman', 'Turnu Magurele'),
      new State(296, 'Teleorman', 'Zimnicea'),
      new State(297, 'Teleorman', 'Videle'),

      new State(298, 'Timis', 'Timisoara'),
      new State(299, 'Timis', 'Lugoj'),
      new State(300, 'Timis', 'Sannicolau Mare'),
      new State(301, 'Timis', 'Jimbolia'),
      new State(302, 'Timis', 'Recas'),
      new State(303, 'Timis', 'Faget'),
      new State(304, 'Timis', 'Buzias'),
      new State(305, 'Timis', 'Deta'),
      new State(306, 'Timis', 'Gataia'),
      new State(307, 'Timis', 'Ciacova'),

      new State(308, 'Tulcea', 'Tulcea'),
      new State(309, 'Tulcea', 'Babadag'),
      new State(310, 'Tulcea', 'Macin'),
      new State(311, 'Tulcea', 'Isaccea'),
      new State(312, 'Tulcea', 'Sulina'),

      new State(313, 'Valcea', 'Ramnicu Valcea'),
      new State(314, 'Valcea', 'Dragasani'),
      new State(315, 'Valcea', 'Babeni'),
      new State(316, 'Valcea', 'Calimanesti'),
      new State(317, 'Valcea', 'Horezu'),
      new State(318, 'Valcea', 'Brezoi'),
      new State(319, 'Valcea', 'Balcesti'),
      new State(320, 'Valcea', 'Berbesti'),
      new State(321, 'Valcea', 'Baile Olanesti'),
      new State(322, 'Valcea', 'Ocnele Mari'),
      new State(323, 'Valcea', 'Baile Govora'),

      new State(324, 'Vaslui', 'Vaslui'),
      new State(325, 'Vaslui', 'Barlad'),
      new State(326, 'Vaslui', 'Husi'),
      new State(327, 'Vaslui', 'Negresti'),
      new State(328, 'Vaslui', 'Murgeni'),

      new State(329, 'Vrancea', 'Focsani'),
      new State(330, 'Vrancea', 'Adjud'),
      new State(331, 'Vrancea', 'Marasesti'),
      new State(332, 'Vrancea', 'Odobesti'),
      new State(333, 'Vrancea', 'Panciu'),

    ];
  }

  getStatesByCounty(countyId) {
    //selecteaza doar din judetul respectiv si apoi sorteaza dupa ordine alfabetica
    return this.getStates()
      .filter(state => state.countryid === countyId)
      .sort((stateA, stateB) => stateA.name.localeCompare(stateB.name));
  }
  
}
